config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :cars

  resources :employees

  resources :customers
  resources :pages

  root 'quotes#index'

  get "/update_price" => "cars#update_price"

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  after_save :check_sold
  belongs_to :car
  belongs_to :customer
  belongs_to :employee
  validates :totalPrice, :employee_id, :customer_id, presence:true
  validates :totalPrice, :numericality => { greater_than_or_equal_to: 0}
  validates :interestRate, :numericality => { greater_than_or_equal_to: 0, :less_than_or_equal_to => 100}
def check_sold
  a = car_id
  c = customer_id
  if isFinal
    Customer.where(:id => c).update_all(:classification => "Active")
    Car.where(:id => a).update_all(:isSold => true)
  else

    Car.where(:id => a).update_all(:isSold => false)

  end
  def reporting
  @revenue = Quote.where(:isFinal => true).sum("totalPrice").to_s
  @salestax = Car.where(:isSold => true).sum(:tax).to_s
  @soldmsrp = Car.where(:isSold => true).sum(:wholeSaleCost).to_s
  @profit = @revenue - @salestax - @soldmsrp

  end

end

end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  helper_method :sort_col, :sort_dir

  # GET /quotes
  # GET /quotes.json
  def index

    @quotes = Quote.joins('JOIN CARS c ON Quotes.car_id = c.id JOIN CUSTOMERS ON Quotes.customer_id = CUSTOMERS.id JOIN EMPLOYEES ON Quotes.employee_id = EMPLOYEES.id ').order(sort_col + " " + sort_dir)

  end
  def profitt
    @revenue = Quote.where(:isFinal => true).sum("totalPrice").to_f
    @salestax = Car.where(:isSold => true).sum(:tax).to_f
    @soldmsrp = Car.where(:isSold => true).sum(:wholeSaleCost).to_f
    @profitt = 0;
    if((@revenue - @salestax - @soldmsrp) >= 0)
      @profitt = @revenue - @salestax - @soldmsrp
    else
      @profitt = (@revenue - @salestax - @soldmsrp * (-1))
    end

      @profitt

  end
  def revenue
    @revenue = Quote.where(:isFinal => true).sum("totalPrice").to_f
  end

  def taxsale
    @salestax = Car.where(:isSold => true).sum(:tax).to_f
  end
  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end
  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }

      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :employee_id, :car_id, :totalPrice, :isFinal, :duration, :interestRate)
    end
  def sort_col
    params[:sort] || "created_at"

  end
  def sort_dir
    %w[desc, asc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
    <script src="../javascripts/amortize.js"></script>
    <script>

        function update_price() {

            var abd = document.getElementById("quote_car_id").value;

            var car_id = abd;
            if (car_id > 0){
            jQuery.ajax({
                url: "/update_price",
                type: "GET",
                data: {"car_id" : car_id},
                dataType: "html",
                success: function(data) {
                    jQuery("#price1").html(data);
                }
            });}
            else{
                $("#price1").val(0);
            }

        }
    </script>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.collection_select(:customer_id, Customer.all, :id, :full_name) %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select(:employee_id, Employee.where(:position => "Sales Person"), :id, :full_name) %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>

    <%= f.collection_select(:car_id, Car.where(:isSold => false).all, :id, :full_car, {:include_blank => true}, {:onchange => "update_price(this.value)", include_blank: " ", :onload => "update_price(this.value)"}) %>


  </div>


    <div class="field">

      <%= f.label "Base price" %><br>
      <%= text_field_tag(:quote_price,"",:id => "price1", onchange: "getInterestRate()") %>

    </div>

    <div class="field">

      <%= f.label :duration %><br>
      <%= f.select(:duration, [0,3,4,5], {onchange: "getInterestRate()"}) %> years

    </div>

    <div class="field">
      <%= f.label "Interest rate" %><br>
      <%= f.text_field(:interestRate, {onchange: "getInterestRate()"})  %> %
    </div>
  <div class="field">
    <%= f.label "Total Price" %><br>
    <%= f.text_field :totalPrice %>
  </div>
  <div class="field">
    <%= f.label "Sold" %><br>
    <%= f.check_box :isFinal %>
  </div>



    <div>
      <button type="button" class="btn btn-info btn-mini" data-toggle="modal" data-target="#financeModal" onclick="getInterestRate()">View Payments</button>
    </div>
    <br>
  <div class="actions">
    <%= f.submit %>
  </div>








    <div id="financeModal" class="modal fade" role="dialog">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Amortization</h4>
          </div>
          <div class="modal-body">
            <p id="showww">

            <br><br>
            </p>
            <p>
              <br>
              <br>

            <table class="table table-hover">
              <thead>
              <tr>
                <th>Payment #</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Interest Paid</th>
                <th>Principle Paid</th>
                <th>Remaining Balance</th>
              </tr>
              </thead>
              <tbody id="letable">



                 <!-- <tr>
                    <td></td>
                    <td>Date</td>
                    <td>Amount</td>
                    <td>Interest Paid</td>
                    <td>Principle Paid</td>
                    <td>Remaining Balance</td>
              </tr>
                  -->
              </tbody>
            </table>
          </div>

          </p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>

      </div>

<script>
  $(document).ready()
  {
  update_price()
  }
</script>

<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %>
<div class="newlink">
<%= link_to 'New Quote', new_quote_path %>
  </div>
<h1>Listing Quotes</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">

  <thead>
    <tr>
      <th><%= sortable "Customers.lastName", "Customer" %></th>
      <th><%= sortable  "Employees.lastName", "Sales Person" %></th>
      <th><%= sortable "make", "" %></th>
      <th><%= sortable "totalPrice", "Total Price"%>       </th>
      <th><%= sortable "duration", ""    %>              </th>
      <th><%= sortable "interestRate", "Interest Rate" %>                  </th>
      <th><%= sortable "created_at", "Quoted On"%>                  </th>
      <th><%= sortable "isFinal", "Sold"  %>    </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.customer.full_name %></td>
        <td><%= quote.employee.full_name %></td>
        <td><%= quote.car.full_car %></td>
        <td>$<%= sprintf("%.2f", quote.totalPrice) %></td>
        <td><%= quote.duration %> years</td>
        <td><%= quote.interestRate %>%</td>
        <td><%= quote.created_at.to_date %></td>
        <td><%= quote.isFinal %></td>
        <td><%= link_to 'Show', quote, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
  </div>
<br>
<div class="newlink">
<%= link_to 'New Quote', new_quote_path%>
</div>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.full_name %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @quote.employee.full_name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.full_car %>
</p>

<p>
  <strong>Price:</strong>
  $<%= @quote.car.price %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @quote.duration %> years
</p>

<p>
  <strong>Interest Rate:</strong>
  <%= @quote.interestRate %>%
</p>

<p>
  <strong>Total Price:</strong>
  $<%= @quote.totalPrice %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @quote.isFinal %>
</p>





<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>