config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :cars

  resources :employees

  resources :customers
  resources :pages

  root 'quotes#index'

  get "/update_price" => "cars#update_price"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :quotes
  validates :firstName, :lastName, presence:true
  def full_name
    "#{lastName}, #{firstName}"
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  helper_method :sort_col, :sort_dir
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.order(sort_col + " " + sort_dir)
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end
  def sort_col
    params[:sort] || "position"

  end
  def sort_dir
    %w[asc, desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:firstName, :lastName, :phone, :position)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label text="First Name" %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label text="Last Name" %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.select :position, ["Inactive", "Sales Person", "Sales Manager", "Finance Manager", "Inventory Manager", "Dealership Owner"] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<div class="newlink">
  <%= link_to 'New Employee', new_employee_path %>
</div>
<h1>Listing Employees</h1>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">

  <thead>
    <tr>
      <th><%= sortable "firstName", "First Name"%></th>
      <th><%= sortable "lastName", "Last Name"%></th>
      <th><%= sortable "phone", "Phone"%></th>
      <th><%= sortable "position", "Position"%></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.firstName %></td>
        <td><%= employee.lastName %></td>
        <td><%= employee.phone %></td>
        <td><%= employee.position %></td>
        <td><%= link_to 'Show', employee, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>
<br>

<div class="newlink">
  <%= link_to 'New Employee', new_employee_path %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @employee.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @employee.lastName %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @employee.phone %>
</p>

<p>
  <strong>Position:</strong>
  <%= @employee.position %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>