config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :cars

  resources :employees

  resources :customers
  resources :pages

  root 'quotes#index'

  get "/update_price" => "cars#update_price"

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  validates :firstName, :lastName, presence:true

  def full_name
    "#{lastName}, #{firstName}"
  end
  def self.search(query)
    where("firstName like ? OR lastName like ?", "%#{query}%", "%#{query}%")
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  helper_method :sort_col, :sort_dir
  # GET /customers
  # GET /customers.json
  def index
    if params[:search]
      @customers = Customer.search(params[:search])
    else
    @customers = Customer.order(sort_col + " " + sort_dir)
    end
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end
  def sort_col
    params[:sort] || "lastName"

  end
  def sort_dir
    %w[asc, desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:firstName, :lastName, :phone, :classification)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label text="First Name" %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label text="Last Name" %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :classification %><br>
    <%= f.select :classification, ["Prospective", "Active"]  %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="newlink">
  <%= link_to 'New Customer', new_customer_path %>
</div>
<h1>Listing Customers</h1>
<%= form_tag customers_path, :method => "GET" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
<div class="media">
  <div class="media-body">
    <table class="table table-hover">

  <thead>
    <tr>
      <th><%= sortable "firstName", "First Name"%></th>
      <th><%= sortable "lastName", "Last Name"%></th>
      <th><%= sortable "phone", "Phone Number"%></th>
      <th><%= sortable "classification", "Status" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.firstName %></td>
        <td> <%= customer.lastName %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.classification %></td>
        <td><%= link_to 'Show', customer, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>
<br>

<div class="newlink">
  <%= link_to 'New Customer', new_customer_path %>
</div>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First Name:</strong>
  <%= @customer.firstName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @customer.lastName %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Classification:</strong>
  <%= @customer.classification %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>