config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  resources :cars

  resources :employees

  resources :customers
  resources :pages

  root 'quotes#index'

  get "/update_price" => "cars#update_price"

end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :quotes
  validates :vin, :make, :model, :color, :wholeSaleCost, :price, :mileage, presence:true
  validates :wholeSaleCost, :price, :mileage, :year,  :numericality => {greater_than_or_equal_to: 0}
  validates :vin, length: { is: 17, message: "The VIN is not 17 characters long"}
  #validates_format_of :price, :with => /^[0-9]+\.[0-9]{2}$/, multiline:true, :message => "price must only contain numbers and contain two decimal places"

  def full_car
    if nil?
      " "
    else
      "#{make} #{model} #{color} #{year} #{vin}"
    end

  end

def self.search(query)
  where("make like ? OR model like ? OR color like?", "%#{query}%", "%#{query}%", "%#{query}%")
end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  helper_method :sort_col, :sort_dir

  def update_price

      @cars = Car.where("id" => params[:car_id]).first.price
      if @cars.nil?
        @cars = 0
      end
      render :partial => 'cars/cars', :object => @cars
  end
  # GET /cars
  # GET /cars.json
  def index
    if params[:search]
      @cars = Car.search(params[:search])
      else
    @cars = Car.order(sort_col + " " + sort_dir)
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    @cars = Car.all
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort_col
    params[:sort] || "vin"

  end
  def sort_dir
    %w[asc, desc].include?(params[:direction]) ? params[:direction] : "asc"
  end




    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:vin, :make, :model, :color, :wholeSaleCost, :price, :isSold, :mileage, :tax, :year)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_cars.html.erb
<script>

        $("#price1").val("<%= escape_javascript(@cars.to_s) %>");

        getInterestRate();

</script>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<script>
  function updateprice(){
    var wholesale = parseFloat(document.getElementById("car_wholeSaleCost").value);
      var price = parseFloat(wholesale + wholesale * .1);
      var tax = parseFloat (price * .043);
      var price = price + tax;
      document.getElementById("car_tax").value = tax.toFixed(2);
      document.getElementById("car_price").value = price.toFixed(2);
  }

</script>

  <div class="field">
    <%= f.label text="VIN" %><br>
    <%= f.text_field :vin %>
  </div>
    <div class="field">
      <%= f.label :year %><br>
      <%= f.text_field :year %>
    </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label text="Whole Sale Price" %><br>
    <%= f.text_field :wholeSaleCost, :onchange => "updateprice()" %>
  </div>
    <div class="field">
      <%= f.label text="Sales Tax" %><br>
      <%= f.text_field :tax, :readonly => true %>
    </div>
  <div class="field">
    <%= f.label text="Marked Up Price With Sales Tax" %><br>
    <%= f.text_field :price, :readonly => true %>
  </div>
    <div class="field">
      <%= f.label :mileage %><br>
      <%= f.text_field :mileage %>
    </div>
  <div class="field">
    <%= f.label text="Sold" %><br>
    <%= f.check_box :isSold %>
  </div>

<!-- I left the sold check box here incase an employee accidentally sold a car and needed to "unsell" it-->

  <div class="actions">
    <%= f.submit %>
  </div>

    <script>
        $(document).ready()
        {
            updateprice()
        }
    </script>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>
<div class="newlink">
  <%= link_to 'New Car', new_car_path %>
</div>
<h1>Listing Cars</h1>

<%= form_tag cars_path, :method => "GET" do %>
<p>
  <%= text_field_tag :search, params[:search] %>
  <%= submit_tag "Search", :name => nil %>
</p>
<% end %>

  <div class="media">
    <div class="media-body">
      <table class="table table-hover">

  <thead>
    <tr>
      <th><%= sortable "vin", "VIN"%></th>
      <th><%= sortable "year", "Year"%></th>
      <th><%= sortable "make", "Make"%></th>
      <th><%= sortable "model", "Model"%></th>
      <th><%= sortable "color", "Color"%></th>
      <th><%= sortable "wholeSaleCost", "Whole Sale Cost"%></th>
      <th><%= sortable "price", "Price"%></th>
      <th><%= sortable "mileage", "Mileage"%></th>
      <th><%= sortable "isSold", "Sold" %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.vin %></td>
        <td><%= car.year %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td>$<%= sprintf("%.2f", car.wholeSaleCost) %></td>
        <td>$<%= sprintf("%.2f",car.price) %></td>
        <td><%= sprintf("%.1f",car.mileage) %></td>
        <td><%= car.isSold %></td> <!-- CONVERT True/False TO NO/YES-->
        <td><%= link_to 'Show', car, class: 'btn btn-mini btn-primary' %></td>
        <td><%= link_to 'Edit', edit_car_path(car), class: 'btn btn-mini btn-success' %></td>
        <td><%= link_to 'Destroy', car, method: :delete, class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  </div>
  </div>
<br>

<div class="newlink">
  <%= link_to 'New Car', new_car_path %>
</div>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>VIN:</strong>
  <%= @car.vin %>
</p>
<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>
<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Whole Sale Cost:</strong>
  <%= @car.wholeSaleCost %>
</p>
<p>
  <strong>Sales Tax:</strong>
  <%= @car.tax %>
</p>
<p>
  <strong>Price:</strong>
  <%= @car.price %>
</p>

<p>
  <strong>Mileage:</strong>
  <%= @car.mileage %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @car.isSold %>
</p>



<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>